version: '3.8'
networks:
  skynet:
    name: skynet
volumes:
  gradleCache:

services:
  ecombasedb:
    image: ecombasedb
    build:
      context: ecombasedb
      dockerfile: ecombasedb.dockerfile

  ecomdevdb:
    container_name: ecomdevdb
    networks:
      - skynet
    build:
      context: ecomdevdb
      dockerfile: ecomdevdb.dockerfile
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    restart: 'no'
  ecomdevdbmigrate:
    container_name: ecomdevdbmigrate
    depends_on:
      - ecomdevdb
    networks:
      - skynet
    build:
      context: ../../
      dockerfile: support/development/dbmigrator/dbmigrator.dockerfile
    volumes:
      - gradleCache:/home/jenkins/.gradle
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    entrypoint: [ "/tmp/migrate-development.sh" ]

  ecomtestdb:
    container_name: ecomtestdb
    build:
      context: ecomtestdb
      dockerfile: ecomtestdb.dockerfile
    networks:
      - skynet
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - "7432:5432"
    tmpfs: /var/lib/postgresql/data:rw
    environment:
      - POSTGRES_DB=ecomtestdb
      - POSTGRES_PASSWORD=password
    restart: 'no'